<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gloamframework</groupId>
    <artifactId>gloam-framework</artifactId>
    <version>DragonBall.SR2.7</version>
    <packaging>pom</packaging>
    <description>glaom framework is base on spring framework which can help you make project more quickly</description>

    <modules>
        <module>gloam-common</module>
        <module>gloam-framework-support</module>
        <module>gloam-property</module>
        <module>gloam-async</module>
        <module>gloam-scanner</module>
    </modules>

    <developers>
        <developer>
            <id>Moxy</id>
            <name>马晓龙</name>
            <email>moxy.mxl@gmail.com</email>
            <url>https://moxy-hub.gitee.io/</url>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache2.0</name>
            <url>https://github.com/moxy-hub/gloam-framework/blob/DragonBall.SR1/LICENSE</url>
        </license>
    </licenses>

    <distributionManagement>
        <!-- 市民云私有库：https://gitlab.eshiyun.info/nexus/content/repositories/zjk-release/-->
        <repository>
            <id>maven-nexus</id>
            <name>Gloam Release Repository</name>
            <url>http://192.168.1.136:8081/repository/wdzh-mix/</url>
        </repository>
        <snapshotRepository>
            <id>maven-nexus</id>
            <name>Gloam Snapshot Repository</name>
            <url>http://192.168.1.136:8081/repository/wdzh-mix/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <spring.cloud.version>2021.0.9</spring.cloud.version>
        <spring.boot.version>2.7.17</spring.boot.version>
        <spring.cloud.alibaba.version>2021.0.5.0</spring.cloud.alibaba.version>
        <gloam.version>DragonBall.SR2.7</gloam.version>
    </properties>

    <dependencies>
        <!-- 基于lombok开发 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>

            <!-- spring boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- spring cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- spring cloud alibaba -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring.cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- ================================= 内部依赖管理 START ===================================== -->

            <!-- 基础工具包-->
            <dependency>
                <groupId>com.gloamframework</groupId>
                <artifactId>gloam-common</artifactId>
                <version>${gloam.version}</version>
            </dependency>

            <!-- 资源扫描包-->
            <dependency>
                <groupId>com.gloamframework</groupId>
                <artifactId>gloam-scanner</artifactId>
                <version>${gloam.version}</version>
            </dependency>

            <!-- 配置重新包-->
            <dependency>
                <groupId>com.gloamframework</groupId>
                <artifactId>gloam-property</artifactId>
                <version>${gloam.version}</version>
            </dependency>

            <!-- 同步工具包-->
            <dependency>
                <groupId>com.gloamframework</groupId>
                <artifactId>gloam-async</artifactId>
                <version>${gloam.version}</version>
            </dependency>

            <!-- 核心环境包-->
            <dependency>
                <groupId>com.gloamframework</groupId>
                <artifactId>gloam-framework-support</artifactId>
                <version>${gloam.version}</version>
            </dependency>

            <!-- ================================= 内部依赖管理 END ===================================== -->

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- 使用2.8以上的maven发布插件，使用xml仓库信息-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>2.8.2</version>
                </plugin>

                <!-- 上传源码 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.0.1</version>
                    <configuration>
                        <attach>true</attach>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>compile</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <!-- apcectj编译器编译源码 -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>aspectj-maven-plugin</artifactId>
                    <version>1.4</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                        <complianceLevel>1.8</complianceLevel>
                    </configuration>
                </plugin>

                <!-- java编译器 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.vm</include>
                    <include>**/*.bpmn</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>